version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cocktails_db
    volumes:
      - mongodb_data:/data/db
    networks:
      cocktails_network:
        aliases:
          - mongodb

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance # Tema opzionale per il pannello
      ME_CONFIG_BASICAUTH_USERNAME: user     # Utente per accedere a mongo-express
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - cocktails_network

volumes:
  mongodb_data:

networks:
  cocktails_network:
